import { About, Faq } from "@/components/About_Components";
import Head from "next/head";



export default function about() {
  return (
    <>
    <Head>
        <title>Land Listing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
    <main className="mt-10">
      <About/>
      <Faq/>
      
    
    </main>
    </>
  )
}
