

import { Features, Hero, Properties } from '@/components/Home_Components'
import Head from 'next/head'



export default function Home() {




  return (
    <>
     <Head>
        <title>Land Listing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main
      
    >
      
      <Hero/>
    <Properties/>
      <Features/>
    
    </main>
    </>
  )
}



